//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Member
{
    public int No { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string CreateAccount { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyAccount { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public Nullable<int> Flag { get; set; }
}

public partial class Member_Get_Result
{
    public int No { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string CreateAccount { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyAccount { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public Nullable<int> Flag { get; set; }
}

public partial class Member_GetByNo_Result
{
    public int No { get; set; }
    public string Name { get; set; }
    public string Phone { get; set; }
    public string CreateAccount { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ModifyAccount { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
    public Nullable<int> Flag { get; set; }
}
