//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class WCFEntities : DbContext
{
    public WCFEntities()
        : base("name=WCFEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Member> Member { get; set; }

    public virtual int Member_Add(string name, string phone, string createAccount, string modifyAccount, Nullable<int> flag)
    {
        var nameParameter = name != null ?
            new ObjectParameter("Name", name) :
            new ObjectParameter("Name", typeof(string));

        var phoneParameter = phone != null ?
            new ObjectParameter("Phone", phone) :
            new ObjectParameter("Phone", typeof(string));

        var createAccountParameter = createAccount != null ?
            new ObjectParameter("CreateAccount", createAccount) :
            new ObjectParameter("CreateAccount", typeof(string));

        var modifyAccountParameter = modifyAccount != null ?
            new ObjectParameter("ModifyAccount", modifyAccount) :
            new ObjectParameter("ModifyAccount", typeof(string));

        var flagParameter = flag.HasValue ?
            new ObjectParameter("Flag", flag) :
            new ObjectParameter("Flag", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Member_Add", nameParameter, phoneParameter, createAccountParameter, modifyAccountParameter, flagParameter);
    }

    public virtual int Member_Delete(Nullable<int> no)
    {
        var noParameter = no.HasValue ?
            new ObjectParameter("No", no) :
            new ObjectParameter("No", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Member_Delete", noParameter);
    }

    public virtual ObjectResult<Member_GetByNo_Result> Member_GetByNo(Nullable<int> no)
    {
        var noParameter = no.HasValue ?
            new ObjectParameter("No", no) :
            new ObjectParameter("No", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Member_GetByNo_Result>("Member_GetByNo", noParameter);
    }

    public virtual int Member_Update(Nullable<int> no, string name, string phone, string modifyAccount, Nullable<int> flag)
    {
        var noParameter = no.HasValue ?
            new ObjectParameter("No", no) :
            new ObjectParameter("No", typeof(int));

        var nameParameter = name != null ?
            new ObjectParameter("Name", name) :
            new ObjectParameter("Name", typeof(string));

        var phoneParameter = phone != null ?
            new ObjectParameter("Phone", phone) :
            new ObjectParameter("Phone", typeof(string));

        var modifyAccountParameter = modifyAccount != null ?
            new ObjectParameter("ModifyAccount", modifyAccount) :
            new ObjectParameter("ModifyAccount", typeof(string));

        var flagParameter = flag.HasValue ?
            new ObjectParameter("Flag", flag) :
            new ObjectParameter("Flag", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Member_Update", noParameter, nameParameter, phoneParameter, modifyAccountParameter, flagParameter);
    }

    public virtual ObjectResult<Member_Get_Result> Member_Get()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Member_Get_Result>("Member_Get");
    }
}
